In [34]:
import os.path
import json
import pandas as pd
import numpy as np

from datetime import date
import calendar

import re #regular expression matching

In [5]:
def raw_data_cleanup(filename):
    """
    load rawdata.json and do basic cleanup
    -enter filename with extension as str, file should be in subdirectory raw_data
    
    param: filename, str
    return: DataFrame
    """
    PATH = "./" + str(filename)
    
    if os.path.isfile(PATH):
        print("{} is located in current directory".format(filename))

        with open(PATH) as json_file:  
            data = json.load(json_file)
            
        df = pd.DataFrame(data,columns = ['date','location','category','keyword'])
        print("{} is imported into dataframe".format(filename))
        
        df.to_csv('./output.csv', index = False)
        # Generate city column from location 
        city_list = []
        for i in df['location']:
            if ',' in i:
                city = i.split(',')[0]
                city_list.append(city)
            else:
                city_list.append(i)
        df['city'] = city_list

        # Datetime transformation
        
        # Check Top places (location) where news are coming from
        city_sort = df['city'].groupby(df['city']).count().sort_values(ascending=False)
        display(city_sort)
        
        # Save DataFrame into csv file
        display(df)
        city_sort.to_csv('./city_sort.csv')
        
        
    else:
        print("{} does not exist in directory. Function was not complete.".format(filename))
    
    return

In [6]:
raw_data_cleanup('test.json')

test.json is located in current directory
test.json is imported into dataframe

city
LOSANGELES      5
NEWYORK         5
EMERYVILLE      4
ROHNERTPARK     3
ATLANTA         2
SANDIEGO        2
PETALUMA        2
IRVINE          1
HOLLYWOOD       1
HOLLAND         1
HAMMOND         1
GREENVILLE      1
GARLAND         1
FAYETTEVILLE    1
FARIBAULT       1
WILMINGTON      1
COOKEVILLE      1
LANSING         1
CALGARY         1
BLACKWELL       1
BETHESDA        1
BELLEVUE        1
AUSTIN          1
APOPKA          1
ANDERSON        1
ALSIP           1
CLEVELAND       1
MONTROSE        1
MILLTOWN        1
RIODEJANEIRO    1
TORONTO         1
TALLINN         1
Seattle         1
SYDNEY          1
SEATTLE         1
SANRAMON        1
SANJOSE         1
SACRAMENTO      1
RALEIGH         1
WAYNE           1
QUINCY          1
POLAND          1
PLEASANTON      1
PHILADELPHIA    1
PASADENA        1
ORLANDO         1
NORTHBORO       1
NEWORLEANS      1
ADA             1
Name: city, dtype: int64

,date,location,category,keyword,city
0,"Aug 3, 2018 11:00 CDT",NEWORLEANS,Real Estate,Cloud,NEWORLEANS
1,"Aug 3, 2018 09:00 PDT",SANDIEGO,Healthcare,Alzheimer's disease,SANDIEGO
2,"Aug 3, 2018 09:00 PDT","PLEASANTON, Calif.",Healthcare and Medical Informatics,Dispense Supplements,PLEASANTON
3,"Aug 3, 2018 10:00 PDT","PETALUMA, Calif.",Entrepreneurship,company time,PETALUMA
4,"Aug 3, 2018 13:00 EDT","POLAND, Ohio",Healthcare,Clime Rd,POLAND
5,"Aug 3, 2018 10:00 PDT","EMERYVILLE, Calif.",Financing and Student Loans,federal student loans,EMERYVILLE
6,"Aug 3, 2018 10:00 PDT","SACRAMENTO, Calif.","Restaurants, Bars, and Catering",Downtown Commons,SACRAMENTO
7,"Aug 3, 2018 12:22 CDT","MILLTOWN, Wis.",Garages and Car Ports,automobiles,MILLTOWN
8,"Aug 3, 2018 12:44 CDT","ADA, Okla.",Civil Engineering,civil engineering,ADA
9,"Aug 3, 2018 14:43 EDT","HOLLAND, Mich.",Home Improvement and Renovations,home improvement,HOLLAND
10,"Aug 3, 2018 15:00 EDT","RALEIGH, N.C.",Business News,Awards,RALEIGH
11,"Aug 3, 2018 15:37 EDT","FARIBAULT, Minn.",Animal Husbandry,Suzette Belgarde,FARIBAULT
12,"Aug 3, 2018 19:48 EDT",NEWYORK,Cryptocurrency,Cryptocurrency,NEWYORK
13,"Aug 3, 2018 19:54 CDT","HAMMOND, La.",Franchising,corporate,HAMMOND
14,"Aug 3, 2018 21:25 EDT","HOLLYWOOD, Fla.",Beauty and Cosmetic Products,Infinite Beauty,HOLLYWOOD
15,"Aug 3, 2018 05:00 PDT","ROHNERTPARK, Calif.",Financial News,dying industry,ROHNERTPARK
16,"Aug 3, 2018 05:00 PDT","EMERYVILLE, Calif.",Financing and Student Loans,college tuition,EMERYVILLE
17,"Aug 3, 2018 08:00 EDT",ATLANTA,Entrepreneurship,African American Marketing firm,ATLANTA
18,"Aug 3, 2018 05:00 PDT","SANRAMON, Calif.",Active and Healthy Living,fitness,SANRAMON
19,"Aug 3, 2018 08:00 EDT","ANDERSON, Ind.",Agriculture and Horticulture,Biocontrol,ANDERSON
20,"Aug 3, 2018 07:00 PDT",LOSANGELES,Marketing,adwords management,LOSANGELES
21,"Aug 3, 2018 07:00 PDT",LOSANGELES,Active and Healthy Living,active lifestyle,LOSANGELES
22,"Aug 3, 2018 10:22 EDT","APOPKA, Fla.",Consumer Electronics,apple watch,APOPKA
23,"Aug 3, 2018 11:00 EDT","WILMINGTON, Del.",System and Data Integration,API,WILMINGTON
24,"Aug 3, 2018 12:00 EDT",SEATTLE,Aeronautics and Aerospace,3D printing,SEATTLE
25,"Aug 2, 2018","SANJOSE, Calif.",Marketing,Advertising and Marketing,SANJOSE
26,"Aug 3, 2018 12:29 EDT","CALGARY, Alberta",Finance,Canadian banks,CALGARY
27,"Aug 2, 2018",CLEVELAND,"Restaurants, Bars, and Catering",William Rini,CLEVELAND
28,"Aug 2, 2018","QUINCY, Mass.",Food and Beverage Manufacturing,fiber,QUINCY
29,"Aug 2, 2018","WAYNE, Pa.",Accounting,Business Solutions,WAYNE
...,...,...,...,...,...
35,"Aug 2, 2018",PHILADELPHIA,Business to Business,8(a),PHILADELPHIA
36,"Aug 2, 2018",NEWYORK,Cryptocurrency,alex mashinsky,NEWYORK
37,"Aug 2, 2018","ROHNERTPARK, Calif.",Financing and Student Loans,family expenses,ROHNERTPARK
38,"Aug 2, 2018","GREENVILLE, S.C.",,concerts,GREENVILLE
39,"Aug 2, 2018","COOKEVILLE, Tenn.",Colleges and Universities,anytime learning,COOKEVILLE
40,"Aug 2, 2018",SANDIEGO,Saas (Software as Service),digital marketing,SANDIEGO
41,"Aug 2, 2018","FAYETTEVILLE, Ark.","Banking, Finance, Insurance",banking,FAYETTEVILLE
42,"Aug 2, 2018","TALLINN, Estonia",Cryptocurrency,blockchain,TALLINN
43,"Aug 2, 2018","ALSIP, Ill.",Franchising,50-Years,ALSIP
44,"Aug 3, 2018",LOSANGELES,Arts and Entertainment,AJ X Deno,LOSANGELES
45,"Aug 3, 2018 08:00 BST","BLACKWELL, England",Food and Beverage Manufacturing,Expansion,BLACKWELL
46,"Aug 3, 2018 06:00 EDT",SYDNEY,Pharmaceuticals and Biotech,Animal Health Solutions,SYDNEY
47,"Aug 2, 2018",NEWYORK,Fashion and Apparel,beaches,NEWYORK
48,"Aug 2, 2018",NEWYORK,Business,Culture,NEWYORK
49,"Aug 2, 2018",LOSANGELES,Non Profit,Ban Needed on Torturous Electroconvulsive Therapy,LOSANGELES
50,"Aug 2, 2018","PETALUMA, Calif.",Entrepreneurship,branding,PETALUMA
51,"Aug 2, 2018","LANSING, Michigan",Utilities,ABATE,LANSING
52,"Aug 2, 2018","EMERYVILLE, Calif.",Active and Healthy Living,ASMR,EMERYVILLE
53,"Aug 2, 2018","EMERYVILLE, Calif.",Financing and Student Loans,federal student loans,EMERYVILLE
54,"Aug 2, 2018","BETHESDA, Md.","Banking, Finance, Insurance",Awards,BETHESDA
55,"Aug 2, 2018",TORONTO,Food and Beverage Manufacturing,Food,TORONTO
56,"Aug 2, 2018","MONTROSE, Colo.","Sports, Fitness, and Recreation",Abel and Ross Reels,MONTROSE
57,"Aug 2, 2018",ATLANTA,Healthcare and Medical News,direct anterior approach total hip arthroplasty,ATLANTA
58,"Aug 2, 2018","ROHNERTPARK, Calif.",Financing and Student Loans,education,ROHNERTPARK
59,"Aug 2, 2018","NORTHBORO, Mass.",Business Technology,information governance,NORTHBORO
60,"Aug 2, 2018","AUSTIN, Texas",IT Security,data protection software,AUSTIN
61,"Aug 2, 2018",LOSANGELES,Sports Equipments,hovershoes,LOSANGELES
62,"Aug 2, 2018","Seattle, WA",Arts and Entertainment,Derby,Seattle
63,"Aug 2, 2018",NEWYORK,Healthcare,Beauty,NEWYORK
64,"Aug 2, 2018",RIODEJANEIRO,Education,Food Innovation,RIODEJANEIRO

In [8]:
with open('test.json') as json_file:  
        data = json.load(json_file)
            
df = pd.DataFrame(data,columns = ['date','location','category','keyword'])

        # Generate city column from location 
city_list = []
for i in df['location']:
    if ',' in i:
        city = i.split(',')[0]
        city_list.append(city)
    else:
        city_list.append(i)
df['city'] = city_list

In [ ]:
# Datetime transformation
abbr_to_num = {name: num for num, name in enumerate(calendar.month_abbr) if num}

date_list = []

for i in df['date']:
    month = abbr_to_num[df['date'][i].split(',')[0].split()[0]] ##这句有问题！
    print(month)
    day = df['date'][i].split(',')[0].split()[1]
    year = df['date'][i].split(',')[1].split()[-1]
    date_str = year + '-' + month + '-' + day
    
    fmt = '%Y-%b-%d'
    
    date_fmt = datetime.datetime.strptime(date_str, fmt)
    
    date_list.append(date_fmt)

date_list

In [39]:
abbr_to_num

{'Apr': 4,
 'Aug': 8,
 'Dec': 12,
 'Feb': 2,
 'Jan': 1,
 'Jul': 7,
 'Jun': 6,
 'Mar': 3,
 'May': 5,
 'Nov': 11,
 'Oct': 10,
 'Sep': 9}

In [45]:
for i in df['date']:
    month = abbr_to_num[df['date'][i].split(',')[0].split()[0]]

KeyError: 'Aug 3, 2018 11:00 CDT'